### ISSUE TITLE
Deeplink handling support with React Native

### ISSUE THREAD

**Issue by Samox** [superwall/react-native-superwall#12]
Hello all,
I'm trying to configure paywall within another paywall following [this doc ](https://superwall.com/docs/presenting-paywalls-from-one-another).
I'm stuck at the deeplink configuration. There is no documentation on how to "handle deeplinking" https://superwall.com/docs/in-app-paywall-previews#handling-deep-links-ios. 

I'm trying to manually add the handler in the AppDelegate.mm but without success. I'd be happy to contribute for the iOS integration :D Is there another documentation I could follow ?

**Comment by yusuftor** [comment]
Hi, there's a better way of doing this. You can use a Custom Placement tap action.

1. Add a `CustomPlacement` tap action to a button on the paywall, specifying a name.
2. Add that name as a placement in a campaign and add the paywall that you want to open.

We will update that guide soon. Just note that you must be using the latest version of the React Native SDK to use this. If that's an issue, feel free to reopen this issue and I will provide some assistance with the deep link stuff.

**Comment by Samox** [comment]
Works great ! I tried it but I think the delay for the campaign to be up to date, and the lack of documentation made me abandon.
Thanks !
