### ISSUE TITLE
Error "Exhaustive Switch Statement" in SuperwallEventInfo+Json.swift when building iOS using EAS

### ISSUE THREAD

**Issue by ShaunPrado** [superwall/react-native-superwall#13]
I'm preparing to deploy my iOS application using the Superwall package. During the build process for the development mode using EAS, I encountered an error in the SuperwallEventInfo+Json.swift file. The error log is as follows:

`[RUN_FASTLANE] 
❌  (node_modules/@superwall/react-native-superwall/ios/Json/SuperwallEventInfo+Json.swift:14:5)

  12 | extension SuperwallEvent {
  13 |   func toJson() -> [String: Any] {
> 14 |     switch self {
     |     ^ switch must be exhaustive
  15 |       case .firstSeen:
  16 |         return ["event": "firstSeen"]
  17 |       case .appOpen:
`

The error suggests that the switch statement is not exhaustive and might be missing some cases of the SuperwallEvent enum.

Steps to Reproduce:
Include @superwall/react-native-superwall in the React Native project.
Attempt to build the iOS project using eas build --profile development-simulator --platform ios --local.
Encounter the error related to the switch statement in the SuperwallEventInfo+Json.swift file.

Environment:
Superwall Version:     "@superwall/react-native-superwall": "^1.2.0",
React Native Version: "react-native": "0.74.1",
Expo SDK Version:     "expo": "^51.0.9",
EAS CLI Version: eas-cli/12.4.1 darwin-arm64 node-v22.8.0
Platform: iOS

Additional Context:
I am using the managed Expo workflow.
If this is a known issue, could you please provide guidance on how to resolve it? Otherwise, any recommendations for a temporary fix would be greatly appreciated.

**Comment by yusuftor** [comment]
Updating to the latest version of the Superwall React Native SDK should solve this (v1.2.6). Can you confirm which version is actually being installed?

**Comment by ShaunPrado** [comment]
Updating to the latest version has solved this issue - thanks!
