### ISSUE TITLE
Is this lib going to work with the new architecture change (Fabric)?

### ISSUE THREAD

**Issue by TowhidKashem** [superwall/react-native-superwall#15]
Hi,

It's not listed here:

https://reactnative.directory/?search=%40superwall%2Freact-native-superwall

And I also couldn't find it on the old spreadsheet:

https://docs.google.com/spreadsheets/d/1F1tI9PQLl_uab3HNYNwgjPVL2r0hJ9VymXcgDp5etdg/edit?gid=312228650#gid=312228650

Will it continue to work after Fabric is made the default architecture as of the next release of RN, version 0.75?

**Comment by ianrumac** [comment]
Hi @TowhidKashem !

While are in the process of testing to ensure our SDK works in compatibility mode, we will also be releasing a new version of the SDK that will support the new architecture with some changes to make it more native to React users.
