### ISSUE TITLE
preloadPaywalls eventNames com.facebook.react.bridge.ReadableNativeMap cannot be cast to com.facebook.react.bridge.ReadableNativeArray

### ISSUE THREAD

**Issue by pyb4430** [superwall/react-native-superwall#21]
Seeing the following error on android when using:
```
Superwall.shared.preloadPaywalls(new Set(['event1', 'event2']));
```

<img src=https://github.com/user-attachments/assets/1827b2df-0975-46ea-9de6-c70b22371361 width=300 />

Using 
```
"@superwall/react-native-superwall": "1.3.4",
"react-native": "0.74.5",
```

It works if I switch it to an array instead of a Set, but typescript wants the Set:
```
Superwall.shared.preloadPaywalls(['event1', 'event2']);
```

**Comment by ianrumac** [comment]
Hey @pyb4430 !
Thanks for the report, the issue has been fixed in the latest version 1.3.5!
