### ISSUE TITLE
Getting this vague error from superwall package.

### ISSUE THREAD

**Issue by covert-oddity** [superwall/react-native-superwall#4]
<img width="312" alt="Screenshot 2024-05-22 at 5 20 32 PM" src="https://github.com/superwall/react-native-superwall/assets/1101938/a9013ab7-1307-41a0-9fb9-6cc55e89bf7a">

The error says:
Title: An error occurred
Message: The operation couldn't be completed. (superwall_react_native.PurchaseResultError error 1.)

What does this error mean and how to debug this?

**Comment by covert-oddity** [comment]
I am using this version
"@superwall/react-native-superwall": "1.1.1",

**Comment by covert-oddity** [comment]
@yusuftor , need help with this please.

**Comment by yusuftor** [comment]
Hey, the error "The operation couldn't be completed." is unfortunately a generic error that comes from either StoreKit or RevenueCat, if you're using them. We just propagate the error we receive. My advice would be to check revenuecat or apple/stackoverflow forums for what might cause that. I can see there are quite a few posts over there with possible causes. Sorry I can't be of more help!
