### ISSUE TITLE
Redeem code action doesnt work 

### ISSUE THREAD

**Issue by EugeniuszX** [superwall/react-native-superwall#6]
Hey, I tried a ready-made template, and when I press the redeem code button, nothing happens. Although on iOS, a modal window for entering the code should open

<img width="1270" alt="image" src="https://github.com/superwall/react-native-superwall/assets/63192915/f545092b-bd53-45ac-be20-d31da6a55467">

**Comment by yusuftor** [comment]
You need to handle the custom action yourself using the `handleCustomPaywallAction(withName:)` function of the `SuperwallDelegate`. Whatever you pass as the `name` in the editor will be the `name` parameter passed to that function. Then it's up to you to display the redemption sheet.
